repos:
    # github will run `pre-commit run --hook-stage manual -a` and then manually black and flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
        stages: [commit, push, manual]

    -   id: trailing-whitespace
        stages: [commit, push, manual]

    -   id: check-json
        stages: [commit, push, manual]

    -   id: pretty-format-json
        stages: [commit, push, manual]

    -   id: check-xml
        stages: [commit, push, manual]

    -   id: detect-private-key
        stages: [commit, push, manual]

    -   id: name-tests-test
        stages: [commit, push, manual]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [commit, push]

    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [commit, push]