name: Upload code coverage data to Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate coverage report
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        coverage run -m pytest .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2