name: Upload code coverage data to Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate coverage report
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        coverage run -m pytest .
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2