name: Upload test data to Thundra Foresight
on: [ push ]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Generate coverage report
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pytest -o junit_logging=all --junit-xml=test-results.xml
      - name: Foresight Test Report Uploader
        uses: actions/upload-artifact@v2
        with:
          name: test-result-python
          path: test-results.xml