PBKDF2_ALGORITHM: str = "RS512"
SALT_BYTES: int = 64
DERIVED_KEY_LENGTH: int = 64
PBKDF2_ITERATIONS: int = 200_000
AUTHORIZATION_TOKEN_EXPIRY_MINUTES: int = 120
PEPPER_KEY: str = "PEPPER"
SECURE_STRING_LENGTH: int = 20
SUPER_ADMIN_ROLE: str = "super_admin"
