PBKDF2_ALGORITHM: str = "RS512"
SALT_BYTES: int = 64
DERIVED_KEY_LENGTH: int = 64
PBKDF2_ITERATIONS: int = 100_000
AUTHORIZATION_TOKEN_EXPIRY_MINUTES: int = 15
PEPPER_KEY: str = "PEPPER"
PEPPER_BYTES: int = 64
SUPER_ADMIN_ROLE: str = "super_admin"
